glue: lxd-ssh: fix first login to noble container
Signed-off-by: Ondrej Kubik <ondrej.kubik@canonical.com>

diff --git a/glue/usr/bin/lxd-ssh b/glue/usr/bin/lxd-ssh
--- a/glue/usr/bin/lxd-ssh
+++ b/glue/usr/bin/lxd-ssh
@@ -44,7 +44,7 @@ set -e
 # Known issues:
 # 1) It takes a few moments for the container to create its host key and start
 #    sshd. Until then attempts to ssh will result in an error.
-hostname="$1"
+hostname="${1}"
 case "$hostname" in
     *.lxd) ;;
     *)
@@ -62,15 +62,17 @@ sync_host_keys() {
     cleanup() { rm -rf "$tmpdir"; }
     tmpdir=$(mktemp -d lxd-ssh.XXXXX)
     trap cleanup INT TERM
-    lxc exec "$container" -- sh -c 'cat /etc/ssh/*.pub 2>/dev/null || echo "Container ssh host keys not found; has it had enough time to boot?" >&2' | while read -r a b; do echo "$hostname ";echo "$a $b";done > "$tmpdir/known_hosts_additions" && \
+    lxc exec "${container}" -- sh -c 'cat /etc/ssh/*.pub 2>/dev/null || echo "Container ssh host keys not found; has it had enough time to boot?" >&2' | while read -r a b; do echo "$hostname ";echo "$a $b";done > "$tmpdir/known_hosts_additions" && \
     	ssh-keygen -H -f "$tmpdir/known_hosts_additions" 2>/dev/null && \
             cat ~/.ssh/known_hosts "$tmpdir/known_hosts_additions" > ~/.ssh/known_hosts.$$ && \
             mv ~/.ssh/known_hosts.$$ ~/.ssh/known_hosts
     cleanup
 }
 
-if ! ssh-keygen -F "$hostname" </dev/null >/dev/null; then
-    sync_host_keys "$hostname" "$container" </dev/null >/dev/null
+if ! ssh-keygen -F "${hostname}" </dev/null >/dev/null; then
+    sync_host_keys "${hostname}" "${container}" </dev/null >/dev/null
 fi
 
-exec lxc exec "$container" -- sshd -i
+# recent ubuntu images have socket activated sshd, so sshd -i silently fails
+# because of the missing privilege separation directory, ensure it's there
+exec lxc exec "${container}" -- sh -c 'mkdir -p /run/sshd;sshd -i'
