glue: cleanup scripts after relocating under usr/bin
Signed-off-by: Ondrej Kubik <ondrej.kubik@canonical.com>

diff --git a/glue/usr/bin/lxd-ssh b/glue/usr/bin/lxd-ssh
--- a/glue/usr/bin/lxd-ssh
+++ b/glue/usr/bin/lxd-ssh
@@ -56,13 +56,13 @@ esac
 container=${hostname%.lxd}
 
 sync_host_keys() {
-    local hostname=$1
-    local container=$2
+    hostname=${1}
+    container=${2}
 
     cleanup() { rm -rf "$tmpdir"; }
-    tmpdir=`mktemp -d lxd-ssh.XXXXX`
+    tmpdir=$(mktemp -d lxd-ssh.XXXXX)
     trap cleanup INT TERM
-    lxc exec "$container" -- sh -c 'cat /etc/ssh/*.pub 2>/dev/null || echo "Container ssh host keys not found; has it had enough time to boot?" >&2' | while read a b c; do echo -n "$hostname ";echo "$a $b";done > "$tmpdir/known_hosts_additions" && \
+    lxc exec "$container" -- sh -c 'cat /etc/ssh/*.pub 2>/dev/null || echo "Container ssh host keys not found; has it had enough time to boot?" >&2' | while read -r a b; do echo "$hostname ";echo "$a $b";done > "$tmpdir/known_hosts_additions" && \
     	ssh-keygen -H -f "$tmpdir/known_hosts_additions" 2>/dev/null && \
             cat ~/.ssh/known_hosts "$tmpdir/known_hosts_additions" > ~/.ssh/known_hosts.$$ && \
             mv ~/.ssh/known_hosts.$$ ~/.ssh/known_hosts
