glue: update lxd helper script
Signed-off-by: Ondrej Kubik <ondrej.kubik@canonical.com>

diff --git a/glue/bin/lxd-ssh b/glue/bin/lxd-ssh
--- a/glue/bin/lxd-ssh
+++ b/glue/bin/lxd-ssh
@@ -62,7 +62,7 @@ sync_host_keys() {
     cleanup() { rm -rf "$tmpdir"; }
     tmpdir=`mktemp -d lxd-ssh.XXXXX`
     trap cleanup INT TERM
-    sudo lxc exec "$container" -- sh -c 'cat /etc/ssh/*.pub 2>/dev/null || echo "Container ssh host keys not found; has it had enough time to boot?" >&2' | while read a b c; do echo -n "$hostname ";echo "$a $b";done > "$tmpdir/known_hosts_additions" && \
+    lxc exec "$container" -- sh -c 'cat /etc/ssh/*.pub 2>/dev/null || echo "Container ssh host keys not found; has it had enough time to boot?" >&2' | while read a b c; do echo -n "$hostname ";echo "$a $b";done > "$tmpdir/known_hosts_additions" && \
     	ssh-keygen -H -f "$tmpdir/known_hosts_additions" 2>/dev/null && \
             cat ~/.ssh/known_hosts "$tmpdir/known_hosts_additions" > ~/.ssh/known_hosts.$$ && \
             mv ~/.ssh/known_hosts.$$ ~/.ssh/known_hosts
@@ -73,6 +73,4 @@ if ! ssh-keygen -F "$hostname" </dev/null >/dev/null; then
     sync_host_keys "$hostname" "$container" </dev/null >/dev/null
 fi
 
-exec sudo lxc exec "$container" -- sshd -i
-
-
+exec lxc exec "$container" -- sshd -i
