glue: update lxd wrapper script
Signed-off-by: Ondrej Kubik <ondrej.kubik@canonical.com>

diff --git a/glue/bin/snapcraft-lxd-wrapper b/glue/bin/snapcraft-lxd-wrapper
--- a/glue/bin/snapcraft-lxd-wrapper
+++ b/glue/bin/snapcraft-lxd-wrapper
@@ -1,5 +1,7 @@
 #!/bin/bash
 
+# set script version, so we have some tracking
+LXD_SCRIPT_VERSION="0.1"
 IDENTITY_FILE="${HOME}/.ssh/id_rsa-lxd"
 PUBLIC_KEY=${IDENTITY_FILE}.pub
 SSH_CONFIG="${HOME}/.ssh/config"
@@ -34,6 +36,10 @@ ensure_ssh_setup () {
 
   # make sure we have lxd-ssh in path
   if [ -z "$(which lxd-ssh)" ];then
+    if [ ! -d ~/bin ]; then
+      mkdir -p ~/bin
+      export PATH=$PATH:${HOME}/bin
+    fi
     curl -s https://raw.githubusercontent.com/kubiko/toolbox/master/glue/bin/lxd-ssh > ~/bin/lxd-ssh
     chmod +x ~/bin/lxd-ssh
   fi
@@ -45,32 +51,51 @@ lxd_ensure () {
   if [ -n "$(which lxd)" ]; then
     # lxd is installed, assuming all is configured
     return
-  fi
-}
+  else
+    # install and configure lxd
+    echo "Installing lxd..."
+    snap install lxd
 
-# install and configure lxd
-lxd_install () {
-  echo "Installing lxd..."
-  snap install lxd
+    # make sure user is in lxd group
+    if [ -e /var/lib/extrausers/group ] && [ -z "$(grep lxd:x:999:${USER} /var/lib/extrausers/group)" ]; then
+      echo "Adding current user to lxd group"
+      sudo sed -i 's|lxd:x:999:.*|lxd:x:999:'"${USER}"'|g' /var/lib/extrausers/group
+      newgrp lxd
+    fi
 
-  # make sure user is in lxd group
-  if [ -e /var/lib/extrausers/group ] && [ -z "$(grep lxd:x:999:${USER} /var/lib/extrausers/group)" ]; then
-    echo "Adding current user to lxd group"
-    sudo sed -i 's|lxd:x:999:.*|lxd:x:999:'"${USER}"'|g' /var/lib/extrausers/group
-    newgrp lxd
-  fi
+    # make sure we have configured ssh setup
+    ensure_ssh_setup
 
-  # make sure lxd is initialised
-  local lxd_dump="$(lxd init --dump)"
-  if [ -n "$(echo "${lxd_dump}" | grep 'storage_pools: \[\]')" ]; then
+    # make sure lxd is initialised
+    local lxd_dump="$(lxd init --dump)"
+    if [ -n "$(echo "${lxd_dump}" | grep 'storage_pools: \[\]')" ]; then
       echo "Initialising lxd..."
       lxd init --auto --storage-backend=dir
       echo -e "#cloud-config\nssh_authorized_keys:\n - $(cat ${PUBLIC_KEY})" | lxc profile set default user.user-data -
       lxc profile show default
-  elif [ -n "$(echo "${lxd_dump}" | grep $(cat ${PUBLIC_KEY}))" ]; then
+    elif [ -n "$(echo "${lxd_dump}" | grep $(cat ${PUBLIC_KEY}))" ]; then
       echo -e "#cloud-config\nssh_authorized_keys:\n - $(cat ${PUBLIC_KEY})" | lxc profile set default user.user-data -
+    fi
   fi
-  ensure_ssh_setup
+}
+
+lxd_ensure_container_runnig () {
+  if [ -z "${1}" ]; then
+    echo "Missing container name"
+    return 1
+  fi
+  local container_name="${1}"
+  local container_status=$(lxc info ${container_name} 2>&1 | awk '$1 ~ "Status" { print $2}')
+  if [ -n "${container_status}" ]; then
+    echo -e "Container ${container_name} already exists, making sure it's running"
+    if [ "Running" != "${container_status}" ]; then
+      return lxc start ${container_name}
+    fi
+    return 0
+  else
+    echo "Container with given name does not exist"
+    return 1
+  fi
 }
 
 lxd_ensure_snapcraft_container () {
@@ -102,13 +127,8 @@ lxd_ensure_snapcraft_container () {
   fi
   local container_name="${2}"
 
-  local container_status=$(lxc info ${container_name} 2>&1 | awk '$1 ~ "Status" { print $2}')
-  if [ -n "${container_status}" ]; then
-    echo -e "Container ${container_name} already exists, making sure it's running"
-    if [ "Running" != "${container_status}" ]; then
-      lxc start ${container_name}
-    fi
-    return 0
+  if ! lxd_ensure_container_runnig ${container_name}; then
+    return "$?"
   fi
 
   # container does not exist, create it
@@ -176,17 +196,27 @@ lxd_snapcraft () {
     else
       echo -e "Not in snapcraft project directory, or container name defined\n"
       print_help_lxd_snapcraft
-      return
+      return 1
     fi
   else
     local container_name="${snapcraft_lxd_container_name}"
   fi
   # check if lxd is installed, if installed assume it's configured as well
-  [ -z "$(which lxd)" ] && lxd_install
+  lxd_ensure
+
   # make sure container is created and running
-  if lxd_ensure_snapcraft_container ${ubuntu_series} ${container_name}; then
+  if [ -z "${ubuntu_series}" ]; then
+    lxd_ensure_container_runnig ${container_name}
+  else
+    lxd_ensure_snapcraft_container ${ubuntu_series} ${container_name}
+  fi
+
+  # run snapcraft command if we have container ready
+  if [ "$?" = "0" ]; then
     echo -e "Running snapcraft in \"${container_name}\" container"
     ssh -t -q ${container_name}.lxd "cd $(pwd | sed 's|'"${HOME}"'|/home/ubuntu/host|g'); snapcraft $@"
+  else
+    return "$?"
   fi
 }
 
